version: '3.2'

services:

  my-logstash:
    image: ernestgwilsonii/my-logstash:1.0.0
    ports:
      - 514:514/udp
      - 514:514
      - 9600:9600
    deploy:
      labels:
        local.description: "Production grade Logstash"
